//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/ActionMap/PlayerMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerMapping : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerMapping"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""53c4daf9-10b6-4403-b3a9-b613d9c9757a"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""54c02ea3-b81f-49fc-aae8-df1dde3026b5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""017194bf-5eb0-49f8-b482-d32824b4ab14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialShoot"",
                    ""type"": ""Button"",
                    ""id"": ""ca59645c-5917-49c2-b36a-6c1389e66c86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ViewPad"",
                    ""type"": ""Value"",
                    ""id"": ""8cdb07c4-76a6-4fd7-beb1-a0b1909f7a58"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""cdcd56cd-f237-4bf1-88ca-2519761f3a91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootGamepad"",
                    ""type"": ""Button"",
                    ""id"": ""33146830-b4d3-43ce-92c9-e35e7c5b77df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementGamepad"",
                    ""type"": ""Value"",
                    ""id"": ""52fa242d-93ec-4a6a-8b93-5625c4553cec"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SpecialShootGamepad"",
                    ""type"": ""Button"",
                    ""id"": ""cf39609b-ff4f-4308-b988-13407a39752f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashGamepad"",
                    ""type"": ""Button"",
                    ""id"": ""bc83fa15-e69f-4b70-ad64-a64ea95956bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d3839d33-874c-4248-b4fb-43b19b1f9a12"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4e882589-52c1-455e-b2c5-ef42e45450d2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""45bbca44-f1d4-4bda-a1a9-53ea0ec24d64"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""55692c94-672b-42a7-8d7f-d3416e3f4133"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8fe49489-9caa-46b8-bffc-b59553def3fd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ecde346f-1a96-4eda-bdb9-63dab121235e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebf991b8-2d8e-4d3e-ae89-111fad77dbfc"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""SpecialShoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb818ff4-9472-4548-955d-7f9fe5eef374"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ViewPad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1c17a3c-17f7-48c8-83e3-8732d428fab7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keybord & Mouse"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09543617-a00a-4249-b9e4-d1420d305343"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DashGamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c20c1753-ec43-4ca5-addb-e789161aabfd"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialShootGamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c73ab0c-2ac0-470f-8b75-55264889c9d7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MovementGamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4855738d-2aed-4ea0-8e39-20ad65421aea"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ShootGamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Interface"",
            ""id"": ""451a3a34-c0f2-4f7e-8844-6f396832c810"",
            ""actions"": [
                {
                    ""name"": ""Button"",
                    ""type"": ""Value"",
                    ""id"": ""7c92529b-43e9-4f42-ad20-7399e264c6bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GamePadButton"",
                    ""type"": ""Value"",
                    ""id"": ""6c2542e0-559f-4d80-aeee-bde9e61a60d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InteractBtn"",
                    ""type"": ""Value"",
                    ""id"": ""1c3efa28-bb21-4c3f-8d92-bd04f0ebf017"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""34c6710b-2903-48c4-9e72-c71ba2824337"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftGamepadButton"",
                    ""type"": ""Value"",
                    ""id"": ""30975d24-91b4-48fa-8b79-6d39629efdfc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""27ba39f8-9d1b-42d6-be0e-c9c912b18b87"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d91d9f7-9be4-4ad5-9746-56c067d29794"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87820e73-56d8-4b89-aac5-f31a5ce613b7"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53c4f9cf-535e-4ad7-84b7-c41e8781cc25"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""780cf770-045c-4d45-ac03-dca3671ecdd5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""4df6f249-bb88-407c-88ce-0b24f168233f"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""6267f6a8-d28f-4f31-964a-a9c1cfb8b037"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""3b2e9797-2bfd-4a0f-811b-69b6c6c1315b"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""c7e8f0a0-eeb7-4d20-b5fa-8e8c6dca7e29"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6c88ae14-7fe2-4128-9ef4-d75555a5659d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""70014efa-11f5-49a5-80be-a7bf37bff9b7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""d8548cac-fa16-4923-bbd3-c49fb4efffc4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""5d495d98-d340-478c-bc9f-1eae95ccc1c7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""6569a0ee-f62a-4fd8-a943-fb3feee7c2b8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftGamepadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8b565f03-9a6c-46ca-a50b-57e91cad8a05"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamePadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63ff1122-5b0a-41f8-a94b-f6dbe21b6793"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamePadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c1d5b3c-04cb-4559-b94a-ab5318842f9d"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamePadButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca5d2060-907c-4c44-ad32-0e4886c38094"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b82a2ac1-7735-4320-9705-4ab24e781622"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keybord & Mouse"",
            ""bindingGroup"": ""Keybord & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_SpecialShoot = m_Player.FindAction("SpecialShoot", throwIfNotFound: true);
        m_Player_ViewPad = m_Player.FindAction("ViewPad", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_ShootGamepad = m_Player.FindAction("ShootGamepad", throwIfNotFound: true);
        m_Player_MovementGamepad = m_Player.FindAction("MovementGamepad", throwIfNotFound: true);
        m_Player_SpecialShootGamepad = m_Player.FindAction("SpecialShootGamepad", throwIfNotFound: true);
        m_Player_DashGamepad = m_Player.FindAction("DashGamepad", throwIfNotFound: true);
        // Interface
        m_Interface = asset.FindActionMap("Interface", throwIfNotFound: true);
        m_Interface_Button = m_Interface.FindAction("Button", throwIfNotFound: true);
        m_Interface_GamePadButton = m_Interface.FindAction("GamePadButton", throwIfNotFound: true);
        m_Interface_InteractBtn = m_Interface.FindAction("InteractBtn", throwIfNotFound: true);
        m_Interface_Pause = m_Interface.FindAction("Pause", throwIfNotFound: true);
        m_Interface_LeftGamepadButton = m_Interface.FindAction("LeftGamepadButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_SpecialShoot;
    private readonly InputAction m_Player_ViewPad;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_ShootGamepad;
    private readonly InputAction m_Player_MovementGamepad;
    private readonly InputAction m_Player_SpecialShootGamepad;
    private readonly InputAction m_Player_DashGamepad;
    public struct PlayerActions
    {
        private @PlayerMapping m_Wrapper;
        public PlayerActions(@PlayerMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @SpecialShoot => m_Wrapper.m_Player_SpecialShoot;
        public InputAction @ViewPad => m_Wrapper.m_Player_ViewPad;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @ShootGamepad => m_Wrapper.m_Player_ShootGamepad;
        public InputAction @MovementGamepad => m_Wrapper.m_Player_MovementGamepad;
        public InputAction @SpecialShootGamepad => m_Wrapper.m_Player_SpecialShootGamepad;
        public InputAction @DashGamepad => m_Wrapper.m_Player_DashGamepad;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Shoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @SpecialShoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecialShoot;
                @SpecialShoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecialShoot;
                @SpecialShoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecialShoot;
                @ViewPad.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnViewPad;
                @ViewPad.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnViewPad;
                @ViewPad.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnViewPad;
                @Dash.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @ShootGamepad.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootGamepad;
                @ShootGamepad.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootGamepad;
                @ShootGamepad.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShootGamepad;
                @MovementGamepad.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovementGamepad;
                @MovementGamepad.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovementGamepad;
                @MovementGamepad.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovementGamepad;
                @SpecialShootGamepad.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecialShootGamepad;
                @SpecialShootGamepad.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecialShootGamepad;
                @SpecialShootGamepad.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpecialShootGamepad;
                @DashGamepad.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDashGamepad;
                @DashGamepad.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDashGamepad;
                @DashGamepad.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDashGamepad;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @SpecialShoot.started += instance.OnSpecialShoot;
                @SpecialShoot.performed += instance.OnSpecialShoot;
                @SpecialShoot.canceled += instance.OnSpecialShoot;
                @ViewPad.started += instance.OnViewPad;
                @ViewPad.performed += instance.OnViewPad;
                @ViewPad.canceled += instance.OnViewPad;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @ShootGamepad.started += instance.OnShootGamepad;
                @ShootGamepad.performed += instance.OnShootGamepad;
                @ShootGamepad.canceled += instance.OnShootGamepad;
                @MovementGamepad.started += instance.OnMovementGamepad;
                @MovementGamepad.performed += instance.OnMovementGamepad;
                @MovementGamepad.canceled += instance.OnMovementGamepad;
                @SpecialShootGamepad.started += instance.OnSpecialShootGamepad;
                @SpecialShootGamepad.performed += instance.OnSpecialShootGamepad;
                @SpecialShootGamepad.canceled += instance.OnSpecialShootGamepad;
                @DashGamepad.started += instance.OnDashGamepad;
                @DashGamepad.performed += instance.OnDashGamepad;
                @DashGamepad.canceled += instance.OnDashGamepad;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Interface
    private readonly InputActionMap m_Interface;
    private IInterfaceActions m_InterfaceActionsCallbackInterface;
    private readonly InputAction m_Interface_Button;
    private readonly InputAction m_Interface_GamePadButton;
    private readonly InputAction m_Interface_InteractBtn;
    private readonly InputAction m_Interface_Pause;
    private readonly InputAction m_Interface_LeftGamepadButton;
    public struct InterfaceActions
    {
        private @PlayerMapping m_Wrapper;
        public InterfaceActions(@PlayerMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @Button => m_Wrapper.m_Interface_Button;
        public InputAction @GamePadButton => m_Wrapper.m_Interface_GamePadButton;
        public InputAction @InteractBtn => m_Wrapper.m_Interface_InteractBtn;
        public InputAction @Pause => m_Wrapper.m_Interface_Pause;
        public InputAction @LeftGamepadButton => m_Wrapper.m_Interface_LeftGamepadButton;
        public InputActionMap Get() { return m_Wrapper.m_Interface; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InterfaceActions set) { return set.Get(); }
        public void SetCallbacks(IInterfaceActions instance)
        {
            if (m_Wrapper.m_InterfaceActionsCallbackInterface != null)
            {
                @Button.started -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnButton;
                @Button.performed -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnButton;
                @Button.canceled -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnButton;
                @GamePadButton.started -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnGamePadButton;
                @GamePadButton.performed -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnGamePadButton;
                @GamePadButton.canceled -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnGamePadButton;
                @InteractBtn.started -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnInteractBtn;
                @InteractBtn.performed -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnInteractBtn;
                @InteractBtn.canceled -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnInteractBtn;
                @Pause.started -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnPause;
                @LeftGamepadButton.started -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnLeftGamepadButton;
                @LeftGamepadButton.performed -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnLeftGamepadButton;
                @LeftGamepadButton.canceled -= m_Wrapper.m_InterfaceActionsCallbackInterface.OnLeftGamepadButton;
            }
            m_Wrapper.m_InterfaceActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Button.started += instance.OnButton;
                @Button.performed += instance.OnButton;
                @Button.canceled += instance.OnButton;
                @GamePadButton.started += instance.OnGamePadButton;
                @GamePadButton.performed += instance.OnGamePadButton;
                @GamePadButton.canceled += instance.OnGamePadButton;
                @InteractBtn.started += instance.OnInteractBtn;
                @InteractBtn.performed += instance.OnInteractBtn;
                @InteractBtn.canceled += instance.OnInteractBtn;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @LeftGamepadButton.started += instance.OnLeftGamepadButton;
                @LeftGamepadButton.performed += instance.OnLeftGamepadButton;
                @LeftGamepadButton.canceled += instance.OnLeftGamepadButton;
            }
        }
    }
    public InterfaceActions @Interface => new InterfaceActions(this);
    private int m_KeybordMouseSchemeIndex = -1;
    public InputControlScheme KeybordMouseScheme
    {
        get
        {
            if (m_KeybordMouseSchemeIndex == -1) m_KeybordMouseSchemeIndex = asset.FindControlSchemeIndex("Keybord & Mouse");
            return asset.controlSchemes[m_KeybordMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnSpecialShoot(InputAction.CallbackContext context);
        void OnViewPad(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnShootGamepad(InputAction.CallbackContext context);
        void OnMovementGamepad(InputAction.CallbackContext context);
        void OnSpecialShootGamepad(InputAction.CallbackContext context);
        void OnDashGamepad(InputAction.CallbackContext context);
    }
    public interface IInterfaceActions
    {
        void OnButton(InputAction.CallbackContext context);
        void OnGamePadButton(InputAction.CallbackContext context);
        void OnInteractBtn(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnLeftGamepadButton(InputAction.CallbackContext context);
    }
}
